### ISSUE TITLE
error installing the plugin on 8.11.4 es

### ISSUE THREAD

**Issue by nadeemhussain** [querqy/querqy-elasticsearch#125]
I'm trying to install the plugin   on 8.11.4 es getting this error 
```

docker run -it docker.elastic.co/elasticsearch/elasticsearch:8.11.4 bash
elasticsearch@5ce2800c67e0:~$ /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch https://github.com/querqy/querqy-elasticsearch/archive/refs/tags/querqy-elasticsearch-1.7.es8114.0.zip
-> Installing https://github.com/querqy/querqy-elasticsearch/archive/refs/tags/querqy-elasticsearch-1.7.es8114.0.zip
-> Downloading https://github.com/querqy/querqy-elasticsearch/archive/refs/tags/querqy-elasticsearch-1.7.es8114.0.zip
-> Failed installing https://github.com/querqy/querqy-elasticsearch/archive/refs/tags/querqy-elasticsearch-1.7.es8114.0.zip
-> Rolling back https://github.com/querqy/querqy-elasticsearch/archive/refs/tags/querqy-elasticsearch-1.7.es8114.0.zip
-> Rolled back https://github.com/querqy/querqy-elasticsearch/archive/refs/tags/querqy-elasticsearch-1.7.es8114.0.zip
Exception in thread "main" java.lang.IllegalStateException: Plugin [.installing-12740214086509187779] is missing a descriptor properties file.
	at org.elasticsearch.plugins.PluginDescriptor.readFromProperties(PluginDescriptor.java:200)
	at org.elasticsearch.plugins.cli.InstallPluginAction.loadPluginInfo(InstallPluginAction.java:858)
	at org.elasticsearch.plugins.cli.InstallPluginAction.installPlugin(InstallPluginAction.java:918)
	at org.elasticsearch.plugins.cli.InstallPluginAction.execute(InstallPluginAction.java:254)
	at org.elasticsearch.plugins.cli.InstallPluginCommand.execute(InstallPluginCommand.java:89)
	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:94)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
	at org.elasticsearch.cli.Command.main(Command.java:50)
	at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
elasticsearch@5ce2800c67e0:~$
```

**Comment by renekrie** [comment]
I assume that this is no longer an issue. You should be able to use a newer Querqy version - but you need to make sure it was built and released for the exact ES version.
